Repository Quaver/Quaver, pull requests merged in 2021-05, with the labels that each got.

#2970 MapsetImporter: Make .qp import more robust
  Quaver.Shared/Database/Maps/MapsetImporter.cs
Labels: Import

#2972 Only show retry button for gameplay results screen
  Quaver.Shared/Screens/Gameplay/GameplayScreenView.cs
  Quaver.Shared/Screens/Results/ResultsScreen.cs
  Quaver.Shared/Screens/Results/UI/Footer/ResultsScreenFooter.cs
Labels: Replays

#2975 Trim GoToObjects input
  Quaver.Shared/Screens/Edit/EditScreen.cs
Labels: Editor, Enhancement

#3016 Make double import more robust
  Quaver.Shared/Database/Maps/MapDatabaseCache.cs
  Quaver.Shared/Database/Maps/MapsetImporter.cs
  Quaver.Shared/Screens/Edit/Dialogs/EditorAddDifficultyFromQuaDialog.cs
  Quaver.Shared/Screens/Edit/EditScreen.cs
  Quaver.Shared/Screens/Editor/EditorScreen.cs
Labels: Bug Fix, Import

#2978 Check if a config file exist before attempting to read it
  Quaver.Shared/Config/ConfigManager.cs
Labels: Bug Fix, Can't Launch
